version: "3.9"

services:
  api:
    build:
      context: ./api
      args:
        - TARGET_ENV=development
    environment:
      - NODE_ENV=development
    container_name: api-ai-dev
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env/.development.env
    restart: always
  # admin:
  #   build: ./admin
  #   container_name: admin-ai-dev
  #   ports:
  #     - "8000:80"
  #   restart: always

  # web:
  #   build: ./web
  #   container_name: web-ai-dev
  #   ports:
  #     - "8080:80"
  #   restart: always
