name: Dev Server Deploy

on:
  push:
    branches: ["dev"]
    paths:
      - "api/**"                # api 폴더 내부의 모든 변경
      - "docker-compose*.yml"   # docker-compose 파일 변경 시에도 배포

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Documents/portfolio_ai_prediction
            git pull origin dev
            docker compose up -d --build api
