name: production Server Deploy on Amazon Web Server EC2

on:
  push:
    branches: ["master"]
    paths:
      - "api/**"                # api 폴더 내부의 모든 변경
      - "docker-compose-master-api.yml"   # docker-compose 파일 변경 시에도 배포

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/portfolio_ai_prediction
            git pull origin master

            mkdir -p api/.env
            echo "${{ secrets.API_ENV }}" > api/.env/production.env

            docker compose -f docker-compose-master-api.yml down
            docker compose -f docker-compose-master-api.yml up -d --build

            rm -f api/.env/production.env
            