name: production API Deploy on EC2

on:
  push:
    branches: ["master"]
    paths:
      - "api/**"                # api 폴더 내부의 모든 변경
      - "docker-compose-master-api.yml"   # docker-compose 파일 변경 시에도 배포

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/portfolio_ai_prediction
            git pull origin master

            docker-compose -f docker-compose-master-api.yml down
            docker-compose -f docker-compose-master-api.yml build --no-cache
            docker-compose -f docker-compose-master-api.yml up -d --force-recreate
            